
- name: print username and password
  hosts: Local
  connection: local
  vars_prompt:
  - name: username
    prompt: Please enter your username
    private: false

  - name: password
    prompt: please enter your password
    private: true  

  tasks:
  - name: printinfo
    ansible.builtin.debug:
      msg: "username is {{ username }}, password is {{ password }}"  

